// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHK7AnpcB94r6l_o0XQ4s6JPdymXLFxI',
    appId: '1:693431235291:web:d1ad22022a207306c5d2fe',
    messagingSenderId: '693431235291',
    projectId: 'cuentas-claras-e5b09',
    authDomain: 'cuentas-claras-e5b09.firebaseapp.com',
    storageBucket: 'cuentas-claras-e5b09.firebasestorage.app',
    measurementId: 'G-XQ3GZKYLS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIukqefPRSsBIs68pzEpBcjmWAdvvoVLY',
    appId: '1:693431235291:android:b48cebf69381706fc5d2fe',
    messagingSenderId: '693431235291',
    projectId: 'cuentas-claras-e5b09',
    storageBucket: 'cuentas-claras-e5b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADs2NPdttUUoc-cn4V19OOu1jUQhZFk90',
    appId: '1:693431235291:ios:97fea9ef1d807916c5d2fe',
    messagingSenderId: '693431235291',
    projectId: 'cuentas-claras-e5b09',
    storageBucket: 'cuentas-claras-e5b09.firebasestorage.app',
    iosBundleId: 'com.example.cuentasClaras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADs2NPdttUUoc-cn4V19OOu1jUQhZFk90',
    appId: '1:693431235291:ios:97fea9ef1d807916c5d2fe',
    messagingSenderId: '693431235291',
    projectId: 'cuentas-claras-e5b09',
    storageBucket: 'cuentas-claras-e5b09.firebasestorage.app',
    iosBundleId: 'com.example.cuentasClaras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABHK7AnpcB94r6l_o0XQ4s6JPdymXLFxI',
    appId: '1:693431235291:web:5a9a513b70296e49c5d2fe',
    messagingSenderId: '693431235291',
    projectId: 'cuentas-claras-e5b09',
    authDomain: 'cuentas-claras-e5b09.firebaseapp.com',
    storageBucket: 'cuentas-claras-e5b09.firebasestorage.app',
    measurementId: 'G-QVX089LPS0',
  );
}
